interactions:
- request:
    body: ''
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      content-type:
      - application/json
      host:
      - api.openai.com
      user-agent:
      - AsyncOpenAI/Python 1.30.1
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - async:asyncio
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 1.30.1
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.5
    method: GET
    uri: https://api.openai.com/v1/models/gpt-4o-foo
  response:
    body:
      string: |
        {
          "error": {
            "message": "The model 'gpt-4o-foo' does not exist",
            "type": "invalid_request_error",
            "param": "model",
            "code": "model_not_found"
          }
        }
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8a16c9fd493817a2-MAA
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Date:
      - Thu, 11 Jul 2024 06:38:09 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      access-control-allow-origin:
      - '*'
      alt-svc:
      - h3=":443"; ma=86400
      content-length:
      - '166'
      openai-processing-ms:
      - '30'
      openai-version:
      - '2020-10-01'
      strict-transport-security:
      - max-age=15724800; includeSubDomains
      x-request-id:
      - req_11757115775014d962c9d2dcb0ed50ad
    status:
      code: 404
      message: Not Found
version: 1
